### ISSUE TITLE
Can't start a new lobby

### ISSUE THREAD

**Issue by Delfite** [Cyconi/LC-Mods-Library#1]
### **Environment Info**
Lethal Company Version: v49
Mod Version(s) Tested: 0.0.1
Mod Config Changes: None.
Additional Installed Mods: BepInExPack-5.4.2100

### **Description**
When attempting to create a new lobby, regardless of the save you select on the lobby creation screen, the console is spammed with the following error repeatedly, resulting in the game being stuck on the ``Loading...`` screen indefinitely. Removing your mod ``CameraPlus-0.0.1`` fixes this issue entirely.
![image](https://github.com/Cyconi/LC-Mods-Library/assets/23504262/776f8eaf-30e9-48c1-b976-f3607ccba602)

**Comment by Cyconi** [comment]
hmmm it might have broke with the new update, what other mods are you using?
while testing the mod alone or with a few others i cant seem to get the same error

**Comment by Delfite** [comment]
> hmmm it might have broke with the new update, what other mods are you using? while testing the mod alone or with a few others i cant seem to get the same error

Here's a video going over how to recreate the issue: https://youtu.be/gufPRbczUyc
The video will show you my testing setup and the steps needed to recreate the issue I'm experiencing.

**Comment by Delfite** [comment]
### **This issue has been closed**
**Reason:** Stale.
